### PR TITLE
[#154] adding integration with Travis+Codecov

### LINKED ISSUE #154: Integration with code coverage service
It'd good to show in an easy way the coverage of the project which is at amazing level of 95%. There are service like:
* https://coveralls.io/
* or https://codecov.io/

which could be used to visualize the coverage.

We have them both integrated in [esl/exml](https://github.com/esl/exml) and [esl/MongooseIM](https://github.com/esl/MongooseIM)

The integration may be as simple as (in rebar.config):

```erlang
{plugins                , [coveralls,
                           {rebar3_codecov,
                            {git, "https://github.com/zofpolkowska/rebar3_codecov.git",
                             {ref, "3d0af19"}}}
                          ]}.

{cover_enabled          , true}.
{cover_export_enabled   , true}.
{coveralls_coverdata    , "_build/test/cover/eunit.coverdata"}.
{coveralls_service_name , "travis-ci"}.
```

Firstly, though, this repo needs to be added to one or both of the services.

### PR DESCRIPTION
**Pull request by ferigis**
[close #154]

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
@ferigis shouldn't we add some badge to the README.md, too?

**Comment by ferigis** [comment]
yes @elbrujohalcon, I am just testing if this works or not. If it works I will add the html in order to see the nice button in the readme
just testing :)

**Comment by michalwski** [comment]
This will not work yet. A `codecov.json` file needs to be created based on `*.coverdata` file. There is a rebar3 plugin for it:

```erlang
{rebar3_codecov, {git, "https://github.com/zofpolkowska/rebar3_codecov.git", {ref, "3d0af19"}}}
```

**Comment by ferigis** [comment]
thanks @michalwski I think it is working now

**Comment by elbrujohalcon** [comment]
Merged and added to #155 as well.

**Pull request merged**
