### PR TITLE
Get rid of the worker_type option

### PR DESCRIPTION
**Pull request by NelsonVides**
We're not planning to implement support for anything other than gen_servers any time soon.

Tackles #194.

### CODE REVIEW

**Review by paulo-ferraz-oliveira — APPROVED** [review]
This should be Ok. I don't see any more references to `worker_type` in the code, either.

**Review by elbrujohalcon — APPROVED** [review]

**Comment by elbrujohalcon** [comment]
I'm not sure why tests fail after merging this branch with `main`. @NelsonVides  can you check?

**Comment by NelsonVides** [comment]
> I'm not sure why tests fail after merging this branch with `main`. @NelsonVides can you check?

I've seen `mess_up_with_store` being flaky in other PRs, sometimes passing and sometimes failing... 🤔

**Comment by NelsonVides** [comment]
There, just a retry and this is green, we've got a flaky test @elbrujohalcon 🤷🏽

**Comment by elbrujohalcon** [comment]
> There, just a retry and this is green, we've got a flaky test @elbrujohalcon 🤷🏽

**Pull request merged**
